sudo apt-get install git
sudo apt-get install lm-sensors
sudo apt-get install openssh-server
sudo apt-get install gcc
sudo apt-get install miro
sudo apt-get install youtube-dl
sudo apt-get install nmap
sudo apt-get install iptables
sudo apt-get install htop
sudo apt-get install mplayer
sudo apt-get install netstart
sudo apt-get install ufw
sudo apt-get install xmms
sudo apt-get install curl
sudo apt-get install ssh
